name: Try

on: push

jobs:
  try-job:
    runs-on: ubuntu-latest
    steps:
    - name: Repository name
    - run: echo ::set-env name=REPOSITORY_NAME::$(echo "$GITHUB_REPOSITORY" | awk -F / '{print $2}' | sed -e "s/:refs//")
    - name: Print Repository name
      run: echo "$REPOSITORY_NAME"
