name: Try

on: push

jobs:
  try-job:
    runs-on: ubuntu-latest
    steps:
    - name: Dump github context
      run: echo "${{ toJson(github) }}"
    - name: Repository name
      run: echo "${{ github.repository.name }}"